### ISSUE TITLE
Error 500 in development server

### ISSUE THREAD

**Issue by sokrat21lapa** [hypertrack/quickstart-react-native#6]
In this image there is a screenshot of an error that appears after trying to call the hypertrack library:
const hypertack = require("hypertrack")(this.accountId, this.secretKey);

![image](https://user-images.githubusercontent.com/56341749/87803757-3aa5b300-c853-11ea-9bdc-aec476566e70.png)
It seems there is something related with the dev api.

**Comment by tulushev** [comment]
Answered in an email
